backend = "glx";
vsync = true;

# Window animations
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;

# Border
corner-radius = 10;
round-borders = 1;

rounded-corners-exclude = [
  "class_g = 'Polybar'"
];

# Opacity
opacity-rule = [
  "90:class_g = 'Alacritty'",
  "90:class_g = 'Alacritty' && focused",
  "50:class_g = 'Alacritty' && !focused"
];

# Blur
blur-method = "dual_kawase";
blur-strength = 4;

blur-background-exclude = [
  "class_g != 'Alacritty'"
];

# Shadows
shadow = true;

